@extends('layouts.app')

@section('content')
<div class="py-6">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center mb-6">
            <h1 class="text-2xl font-semibold text-gray-900">Sales Invoice #{{ $invoice->invoice_number }}</h1>
            <div class="space-x-3">
                <a href="{{ route('sales.invoices.show', $invoice) }}" class="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 text-sm">Back</a>
                <button onclick="window.print()" class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 text-sm">Print</button>
            </div>
        </div>
        <div class="bg-white rounded-lg shadow overflow-hidden p-6">
            <div class="border-b pb-4 mb-4">
                <h2 class="text-xl font-bold">{{ $invoice->company->name ?? 'Company' }}</h2>
                <p class="text-sm text-gray-500">Invoice #: {{ $invoice->invoice_number }}</p>
                <p class="text-sm text-gray-500">Date: {{ $invoice->invoice_date }}</p>
                <p class="text-sm text-gray-500">Due Date: {{ $invoice->due_date }}</p>
            </div>
            <div class="border-b pb-4 mb-4">
                <h3 class="font-semibold">Customer</h3>
                <p class="text-sm">{{ $invoice->customer->name ?? '' }}</p>
            </div>
            @if($invoice->items->isNotEmpty())
            <table class="min-w-full divide-y divide-gray-200 mb-4">
                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Item</th>
                        <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase">Quantity</th>
                        <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase">Price</th>
                        <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase">Total</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200">
                    @foreach($invoice->items as $item)
                    <tr>
                        <td class="px-4 py-2 text-sm">{{ $item->product->name ?? $item->description ?? '' }}</td>
                        <td class="px-4 py-2 text-sm text-right">{{ $item->quantity }}</td>
                        <td class="px-4 py-2 text-sm text-right">{{ number_format($item->price, 2) }}</td>
                        <td class="px-4 py-2 text-sm text-right">{{ number_format($item->total, 2) }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @endif
            <div class="text-right space-y-1">
                <p class="text-sm">Subtotal: {{ number_format($invoice->subtotal, 2) }}</p>
                @if($invoice->tax_amount > 0)
                <p class="text-sm">Tax: {{ number_format($invoice->tax_amount, 2) }}</p>
                @endif
                <p class="text-lg font-bold">Total: {{ number_format($invoice->total, 2) }}</p>
            </div>
            <div class="mt-6 pt-4 border-t text-xs text-gray-400 text-center">
                <p>Generated by ZERP System</p>
            </div>
        </div>
    </div>
</div>
@endsection
